import React, { useState } from 'react';
import { Layout } from '@/components/Layout';
import { QuizList } from '@/components/quiz/QuizList';
import { QuizBuilder } from '@/components/quiz/QuizBuilder';
import { QuizGenerator } from '@/components/quiz/QuizGenerator';
import { QuizTaker } from '@/components/quiz/QuizTaker';
import { Quiz, QuizAttempt } from '@/types/quiz';
import { BrainCircuit } from 'lucide-react';
import { generateId, saveQuizAttempt } from '@/lib/storage';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';

// Mock Data
const MOCK_QUIZZES: Quiz[] = [
    {
        id: '1',
        title: 'Introduction to React',
        description: 'Test your knowledge of Components, Props, and State.',
        questions: [
            {
                id: 'q1',
                quizId: '1',
                type: 'multiple_choice',
                text: 'What is a Hook in React?',
                options: ['A fishing tool', 'A special function to let you "hook into" React features', 'A class component', 'A Redux store'],
                correctAnswer: 'A special function to let you "hook into" React features',
                points: 10
            },
            {
                id: 'q2',
                quizId: '1',
                type: 'multiple_choice',
                text: 'Which hook is used for side effects?',
                options: ['useState', 'useEffect', 'useContext', 'useReducer'],
                correctAnswer: 'useEffect',
                points: 10
            }
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
        isAiGenerated: false
    },
    {
        id: '2',
        title: 'World History Trivia',
        description: 'A fun quiz generated by AI to test general history knowledge.',
        questions: [],
        createdAt: new Date(),
        updatedAt: new Date(),
        isAiGenerated: true
    }
];

type ViewState = 'list' | 'create' | 'generate' | 'take';

export default function QuizPage() {
    const [view, setView] = useState<ViewState>('list');
    const [quizzes, setQuizzes] = useState<Quiz[]>(MOCK_QUIZZES);
    const [activeQuiz, setActiveQuiz] = useState<Quiz | null>(null);
    const { user } = useAuth();
    const { toast } = useToast();

    const handleSaveQuiz = (quizData: any) => {
        const newQuiz: Quiz = {
            id: crypto.randomUUID(),
            ...quizData,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            isAiGenerated: quizData.isAiGenerated || false
        };
        setQuizzes([newQuiz, ...quizzes]);
        setView('list');
    };

    const handleSelectQuiz = (quiz: Quiz) => {
        // Only allow taking if it has questions
        if (quiz.questions.length > 0) {
            setActiveQuiz(quiz);
            setView('take');
        } else {
            alert("This quiz has no questions yet!");
        }
    };

    return (
        <Layout>
            <div className="h-full flex flex-col space-y-6">
                {view === 'list' && (
                    <>
                        <div className="flex items-center justify-between">
                            <div className="space-y-1">
                                <h1 className="text-3xl font-bold font-display flex items-center gap-3">
                                    <BrainCircuit className="h-8 w-8 text-primary" />
                                    Quiz Engine
                                </h1>
                                <p className="text-muted-foreground">
                                    Test your knowledge with AI-generated quizzes or create your own.
                                </p>
                            </div>
                        </div>
                        <QuizList
                            quizzes={quizzes}
                            onSelectQuiz={handleSelectQuiz}
                            onCreateQuiz={() => setView('create')}
                            onGenerateQuiz={() => setView('generate')}
                        />
                    </>
                )}

                {view === 'create' && (
                    <QuizBuilder
                        onSave={handleSaveQuiz}
                        onCancel={() => setView('list')}
                    />
                )}

                {view === 'generate' && (
                    <QuizGenerator
                        onQuizGenerated={handleSaveQuiz}
                        onCancel={() => setView('list')}
                    />
                )}

                {view === 'take' && activeQuiz && (
                    <QuizTaker
                        quiz={activeQuiz}
                        onComplete={(result) => {
                            const attempt: QuizAttempt = {
                                id: generateId(),
                                quizId: activeQuiz.id,
                                userId: user?.id || 'anonymous',
                                startedAt: result.startedAt,
                                completedAt: result.completedAt,
                                score: result.score,
                                maxScore: result.maxScore,
                                answers: result.answers
                            };
                            saveQuizAttempt(attempt);
                            toast({
                                title: "Quiz Completed!",
                                description: `You scored ${result.score}/${result.maxScore}`,
                            });
                        }}
                        onExit={() => {
                            setActiveQuiz(null);
                            setView('list');
                        }}
                    />
                )}
            </div>
        </Layout>
    );
}
